### ISSUE TITLE
Historical data limitations

### ISSUE THREAD

**Issue by gmartsenkov** [spotware/open-api-docs#1]
Hello folks, 
I'm not sure if this is the right place to post but thought it might help others.
I've been successfully using `ProtoOAGetTickDataReq` to fetch tick data however looks like there is no data before `Fri Feb 24 2017 13:59:56 GMT+0000` for `EURUSD ` which seems unusual. Couldn't find any related information on the forums, if there is some limitation it would be good to have it in the docs.

Thanks!

**Comment by afhacker** [comment]
Hi,

The amount of tick data is based on your broker available historical data, and every broker historical data amount differs.

Maybe that's the maximum amount of available tick data for EURUSD, you can verify this by using cTrader desktop back tester.

**Comment by gmartsenkov** [comment]
Thanks, that makes sense @afhacker. Might be beneficial to include that in the docs so people don't wonder about it. Feel free to close the issue. Thanks again!
